### ISSUE TITLE
Bug: won't trigger webhooks

### ISSUE THREAD

**Issue by GautierDele** [ComfortablyCoding/strapi-plugin-publisher#10]
Hello,

It seems like your plugin doesn't trigger webhooks.
Basically when the publish / unpublish event gets triggered, it seems like my webhoobs related to publish and unpublish event are not launched

**Comment by ComfortablyCoding** [comment]
Hello @GautierDele,

Thank you for pointing that out, this should be fixed in the next release.

**Comment by GautierDele** [comment]
Thank you @ComfortablyCoding :)
