### ISSUE TITLE
Mode missing for ActionDateTimePicker

### ISSUE THREAD

**Issue by FlashThePlayer** [ComfortablyCoding/strapi-plugin-publisher#108]
Hi, 
I do think the mode property for the ActionDateTimePicker component is missing? 
Under admin/src/components/Action/Action.js the ActionTimePicker is build like

`<ActionTimePicker onChange={handleDateChange} executeAt={executeAt} isCreating={isCreating} isEditing={isEditing} />`
			
But i guess it should be 

`<ActionTimePicker
				onChange={handleDateChange}
				executeAt={executeAt}
				isCreating={isCreating}
				isEditing={isEditing}
        mode={mode}
			/>`

Without the mode attribute the header of the date picker looks like this 
<img width="276" alt="Screenshot 2023-10-05 at 11 55 13" src="https://github.com/ComfortablyCoding/strapi-plugin-publisher/assets/32594969/71000ea6-959b-48d0-aad1-88f3bfd7395c">

With the attribute set I get the corrcet display
<img width="283" alt="Screenshot 2023-10-05 at 11 54 07" src="https://github.com/ComfortablyCoding/strapi-plugin-publisher/assets/32594969/d562f65a-79e8-4f03-889d-b165d83122b3">

Also how do you like feature requests?
I currently the date format is _not_ changeable? 
Is it possible that you could add a locale attribute to the settings like the same way you do step? 
Or is a pull request better for a request like this?

Anyway thx for the plugin, it makes live way easier!

**Comment by ComfortablyCoding** [comment]
Thanks for the report!

That looks to be the case, not sure how that got through :)

In terms of feature requests a PR over an issue is fine. PRs are always welcome. 

If you end up doing a PR for both of the mentioned things I would prefer they each be done in their own PRs. I try to keep it to one PR per bug/feature etc.
