### ISSUE TITLE
User interface unresponsive

### ISSUE THREAD

**Issue by westende** [ComfortablyCoding/strapi-plugin-publisher#114]
Strapi version: 4.14.3
Publisher plugin version: 1.5.0
Nodejs version: 18.18

The UI for selecting a (un)publish date and time is very slow. Also after setting a publish and/or an unpublish date the entire UI becomes very very slow. It seems this plugin is intercepting all kinds of interaction events causing the entire interface to slow down.

**Comment by ComfortablyCoding** [comment]
It's possible some update to the design system has caused an issue again. This plugin does not listen for any interaction evens that should cause the UI to slow down.

The datepicker is from the strapi admin UI so performance is somewhat dependant on them.

What version of the strapi design system are you on? I will see if I can reproduce this issue.

**Comment by westende** [comment]
I have tried to isolate the issue. I have created a new Strapi project with `npx create-strapi-app@latest my-project --quickstart`. Version 4.14.4.
I have added the publisher plugin. Version 1.5.0.
The lag is there. @strapi/ui-primitives is at version 1.12.2.

**Comment by westende** [comment]
Something is up with the Strapi DatePicker. If I increase the step size the performance issue is decreased. I will try to investigate further today or tomorrow.

**Comment by ComfortablyCoding** [comment]
Yes, the more items you lad in for the time selection the worse the performance will be. I believe the actual time picker component from the design system has this issue itself.

Generally it's recommended to increase the skip to 30 or higher. You will see a performance increase if you do.

The default of one was to prevent a breaking change when this setting was introduced.

**Comment by westende** [comment]
Yes. I will follow this up in the Strapi project. Thank you for your quick communication.

**Comment by westende** [comment]
This is related to https://github.com/strapi/design-system/issues/1170.
