### ISSUE TITLE
Unpublish button text is overlapping on small screens

### ISSUE THREAD

**Issue by Kapcash** [ComfortablyCoding/strapi-plugin-publisher#115]
Hi!

Just a UI feedback that the buttons texts are overlapping, which make them unreadable, on small screens or when you reduce the window size, as shown on the following screenshot:

<img width="253" alt="strapi-publisher-text-overlap" src="https://github.com/ComfortablyCoding/strapi-plugin-publisher/assets/10612835/168d1a8d-2210-499f-b1f8-9357edd488cb">

I think the text should be able to wrap when it doesn't have enough width to be in one line.

**Comment by ComfortablyCoding** [comment]
Thanks, I'll look into this. Unfortunately the strapi design system is not responsive yet which leads to issues like this.

I will see what I can do to fix this manually.

**Comment by ComfortablyCoding** [comment]
I think what would be ideal here is to change the text to just `publish` and `unpublish` with some sort of description text under it.

If you have any suggestions let me know.

**Comment by ComfortablyCoding** [comment]
This should now be fixed in the latest release
