### ISSUE TITLE
requiring functions from other file breaks build

### ISSUE THREAD

**Issue by TasosBak** [ComfortablyCoding/strapi-plugin-publisher#120]
Whenever I try to require a funtion from another file, the build process strops at "Admin UI built successfully". Do you have any suggestions? 
 
 
 Versions: 

```
    "@strapi/strapi": "4.14.0",
    "strapi-plugin-publisher": "^1.5.0",
```

config/plugins.js file
```
const { myFunction } = require("../utils");

module.exports = ({ env }) => ({
    'publisher': {
        enabled: true,
        config: {
            hooks: {
                afterPublish: async ({
                    strapi,
                    uid,
                    entity
                }) => {
                    myFunction(uid, entity);
                },
                afterUnpublish: async ({
                    strapi,
                    uid,
                    entity
                }) => {
                    myFunction(uid, entity);
                },
            },
            components: {
                dateTimePicker: {
                    step: 5
                }
            }
        },
    },
});
```

**Comment by ComfortablyCoding** [comment]
Thanks for the report, I will look into this.

It does look like this is something wrong with strapi in general for this use case as opposed to this plugin.

**Comment by ComfortablyCoding** [comment]
This seems to be something specific to your setup as I had no issue doing this with my own fresh installation.

Versions were the same as yours.

**Comment by TasosBak** [comment]
did you do yarn build and it completed? Forgot to mention that yarn develop works for me too but yarn build breaks.

**Comment by TasosBak** [comment]
Nevermind, it probably has something to do with my setup because I tried importing a dummy function and it worked so it has something to do with the functionality of the functions I'm importing and not the importing itself. 

Thanks a lot for looking into it!
