### ISSUE TITLE
Enabling the plugin in certain collection/single types

### ISSUE THREAD

**Issue by TasosBak** [ComfortablyCoding/strapi-plugin-publisher#122]
It would be nice if we could config the collection/single types where we want the plugin to work. We difficult would that be? I could work on a pr with some guidance!

**Comment by ComfortablyCoding** [comment]
It shouldnt be to difficult. 

- add a plugin setting to control it, default should be all.
- in https://github.com/ComfortablyCoding/strapi-plugin-publisher/blob/master/admin/src/components/ActionManager/ActionManager.js#L10
  - fetch settings with the `useSettings` hook (https://github.com/ComfortablyCoding/strapi-plugin-publisher/blob/master/admin/src/hooks/useSettings.js)
  - check if entry.slug is within the allowed uids.

**Comment by TasosBak** [comment]
I've opened an PR, feel free to check it whenever you can!

**Comment by ComfortablyCoding** [comment]
Thanks! Will have a look at it over the weekend.

**Comment by ComfortablyCoding** [comment]
This is now released and available in v1.5.4
