### ISSUE TITLE
Future publish date did not work with items in API

### ISSUE THREAD

**Issue by suil** [ComfortablyCoding/strapi-plugin-publisher#123]
after I followed instructions https://market.strapi.io/plugins/strapi-plugin-publisher, I was able to see publish panel for an item i created.

However, when I set a future publish data for the new item, The API endpoint still shows the item.

anything wrong with what i did?

**Comment by ComfortablyCoding** [comment]
Is the item pubished already?

The expectation is that the item should still be in draft. The plugin will handle publishing at the date specified and it should then show up in the API as published.

**Comment by ComfortablyCoding** [comment]
Clsing due to inactivity, will re-open if needed
