### ISSUE TITLE
Publisher section not added to the informations

### ISSUE THREAD

**Issue by rodgeraraujo** [ComfortablyCoding/strapi-plugin-publisher#25]
I have install and enabled the plugin, but unfortunately, the section Publisher not apear at the content-type informations.

Any help?

`config/server.ts`:
```ts
export default ({ env }) => ({
  //...
  cron: {
    enabled: true,
  },
});
```

`config/plugins.ts`:
```ts
export default ({ env }) => ({
    //...
    publisher: {
      enabled: true,
    },,
});
```

`Plugin version`: "strapi-plugin-publisher": "^1.1.3"
`Strapi version`: "@strapi/strapi": "4.3.4"

![image](https://user-images.githubusercontent.com/20842252/185158605-a2024a87-1b6d-4b57-a38b-5f1a835de9b3.png)

**Comment by ComfortablyCoding** [comment]
Did you run a clean rebuild (delete `.cache` and `build` folders) of the strapi admin? That usually fixes these sort of issues.

**Comment by rodgeraraujo** [comment]
> Did you run a clean rebuild (delete `.cache` and `build` folders) of the strapi admin? That usually fixes these sort of issues.

Yeah, I delete `.cache`, `dist`,  `build`, `node_modules` and still not working as expected.

I have update my `admin`, any chance this affect the plugin comportament?

**Comment by rodgeraraujo** [comment]
@ComfortablyCoding after a time, working, like magic the buttons apear in the screen, thanks for the time. I think is all working now!

**Comment by Zenith-Lair** [comment]
@rodgeraraujo Mine is not showing. I've clean build everything. However, it's not showing up...

**Comment by Zenith-Lair** [comment]
Oh, never mind, you actually needs to save the record first before the publisher options show up...
