### ISSUE TITLE
[bug] action buttons not respecting role permissions

### ISSUE THREAD

**Issue by soapwong703** [ComfortablyCoding/strapi-plugin-publisher#34]
We are using the author role that come with strapi, and the publisher setting is editiable by author which doesn't have publishing right.

![螢幕截圖 2022-10-18 下午5 02 20](https://user-images.githubusercontent.com/68498079/196386951-645babb1-f024-459a-ac16-fde312c5d499.png)

**Comment by ComfortablyCoding** [comment]
Thanks for the report, I will look into this.

**Comment by nttanh6299** [comment]
Hi , is this bug fixed?
I have the same issue, maybe I use patch-package to temporarily fix this.

**Comment by ComfortablyCoding** [comment]
No, it has not been fixed yet. Still have not found a way to access and/or check the current users field permissions.

**Comment by nttanh6299** [comment]
Currently I am using patch-package to override your file. Its not the best solution but at least solved the problem.
```jsx
import React from 'react';
import { useParams } from 'react-router-dom';
import { useSelector } from "react-redux";
import _get from 'lodash/get';
import { useCMEditViewDataManager, auth } from '@strapi/helper-plugin';
import { Box } from '@strapi/design-system/Box';
import { ActionLayoutHeader } from './ActionLayoutHeader';
import { Action } from '../Action';

const actionModes = ['publish', 'unpublish'];

const hasPublishPermission = (permissions, localeCode, createdById) => {
  const userInfo = auth.getUserInfo();
  if (permissions) {
    const hasPermission = permissions.some((permission) => {
		const hasLocalePermission = _get(permission, "properties.locales", []).includes(localeCode);
		const hasCreatorRole = _get(permission, 'conditions', []).includes('admin::is-creator');
		const hasSameCreatorRole = _get(permission, 'conditions', []).includes('admin::has-same-role-as-creator');

		if (hasCreatorRole && !hasSameCreatorRole) {
			return hasLocalePermission && userInfo.id === createdById;
		} else if (!hasCreatorRole && hasSameCreatorRole) {
			return hasLocalePermission && userInfo.id !== createdById;
		}
		return hasLocalePermission;
	}); 

    if (hasPermission) {
      return true;
    }
  }

  return false;
};

const usePublishPermission = () => {
	const { allLayoutData, initialData } = useCMEditViewDataManager();
	const { uid } = allLayoutData.contentType;
	const { collectionTypesRelatedPermissions } = useSelector(
		(state) => state.rbacProvider
	);

	const locale = _get(initialData, "locale", "");
	const createdById = _get(initialData, 'createdBy.id', -1)

	const contentTypePermissions = collectionTypesRelatedPermissions[uid];
	const publishPermissions = _get(
		contentTypePermissions,
		"plugin::content-manager.explorer.publish",
		[]
	);

	return {
		hasPermission: hasPublishPermission(publishPermissions, locale, createdById)
	}
}

const ActionLayout = () => {
	const { slug, hasDraftAndPublish, isCreatingEntry } = useCMEditViewDataManager();
	const params = useParams();
	const id = _get(params, 'id', null);
	const currentEntityId = Number(id);

	if (!hasDraftAndPublish || isCreatingEntry) {
		return null;
	}

	const { hasPermission } = usePublishPermission()

	if (!hasPermission) {
		return null;
	}

	return (
		<Box marginTop={4}>
			<ActionLayoutHeader />
			{actionModes.map((m, index) => (
				<Action mode={m} key={index} entitySlug={slug} entityId={currentEntityId} />
			))}
		</Box>
	);
};

export { ActionLayout };
```

**Comment by IvoNet** [comment]
I would like to reopen this one because it does not seem to solve the whole problem.
Now the whole admin panel seems to freeze after and "Author" with edit rights but no publish rights has created a new item and saved it.
Using publisher v1.3.8 and strapi v4.12.0

**Comment by ComfortablyCoding** [comment]
Strange, during testing it seemed to work as expected.

It freezes after what? 

When installing the new version was a clean rebuild done (i.e. .cache and build folder removed)?

**Comment by IvoNet** [comment]
Ok how to replay:

Tech info:
- Open Source version Strapi v4.12.0
- publisher plugin v1.3.8
- I have the standard 3 Roles (Admin / Editor / Author)
- Admin can do all
- Editors can create/edit and publish certain Content-Types
- Authors can only create/edit certain Content-Types (when created by someone of the same role) but never publish

When I create a new "News" Content-Type item as an Author and save it it should always be saved as a "Draft" version. That seems to happen but after that, the admin dashboard does not refresh anymore. After about 30 seconds the browser gives a popup with a notification if I want to wait or exit the page as it does not seem to respond.
I've waited a couple of times but nothing happens anymore

**Comment by ComfortablyCoding** [comment]
The only thing that has changed from when it worked was this plugins version update? Because I did not experience that behaviour. 

Although it was tested on 4.11.x not 4.12.0, it's possible something was removed on Strapis side in this version that is causing it.

Is their anything in the console?

**Comment by IvoNet** [comment]
No I actually tested it on strapi version 4.9.2 and had the same problem and then I upgraded to 4.12.0 and it still went wrong

**Comment by ComfortablyCoding** [comment]
I have tried to reproduce this issue on a fresh install of strapi and cannot.

- Strapi Version: `4.12.0`
- strapi-plugin-publisher: `1.3.8`

Given this I would assume this issue is not caused by this plugin and is from something else.
