### ISSUE TITLE
[feature] increase the time picker steps

### ISSUE THREAD

**Issue by Rgeelen** [ComfortablyCoding/strapi-plugin-publisher#36]
Hello,

First of all, thank you for the great plugin. I want to request a feature that improves the publication time setting.

The time picker next to the publish date is displayed per minute. Can this be adjusted to 15 minutes intervals? This functionality is supported by the Strapi [TimePicker](https://design-system-git-main-strapijs.vercel.app/?path=/docs/design-system-components-timepicker--base).

Optionally let users configure the interval option.

Screenshot
<img width="306" alt="image" src="https://user-images.githubusercontent.com/4224426/207271273-57686d56-d159-4c27-965e-6681b7e0a5a1.png">

Have a nice day.

**Comment by alvarlaigna** [comment]
Same wish here to have configurable steps. Ideally, by half an hour and/or manual editing. Thanks for great work!

**Comment by ComfortablyCoding** [comment]
Adding it as a configurable option should be possible. I will look into adding this over the weekend.

**Comment by ComfortablyCoding** [comment]
This functionality has been added in the latest release (v1.2.0)
