### ISSUE TITLE
[feature] Query for Scheduled Dates

### ISSUE THREAD

**Issue by Jahorse** [ComfortablyCoding/strapi-plugin-publisher#40]
Hi there, I love the plugin you've written, it has been super easy to set up and use. One feature I'm trying to add to my website is a display showing the upcoming posts and their publish dates. It seems the REST endpoint `/publisher/actions` has this info, but it requires an admin token and it doesn't seem to be configurable to give access to other roles.

Is this something that could be added, or do you have any pointers for how I could implement it? I wouldn't mind doing it myself but I don't have any experience writing plugins so the overhead of learning all that makes it a bit prohibitive for me.

**Comment by Jahorse** [comment]
Thanks for picking this up! Is there anything I can do to help move the PR along? If I pull it and build it into my devo website, would I be able to access the API?

**Comment by ComfortablyCoding** [comment]
This functionality has been added in the latest release (v1.2.0)
