### ISSUE TITLE
There are bugs like this in the release plug-in

### ISSUE THREAD

**Issue by guoduhw** [ComfortablyCoding/strapi-plugin-publisher#44]
![1673491498504](https://user-images.githubusercontent.com/4437474/211963847-9bad547d-b134-4c49-92ab-c0243124dbf8.png)

**Comment by ComfortablyCoding** [comment]
Sorry I am not fully understanding the issue, can you expand on it a bit? 

If it has anything to do with the DateTimePicker itself that is a strapi issue and not the plugin itself. The component itself comes from [strapis design system](https://github.com/strapi/design-system) and I recommend to file the issue there.

Closing for now until it can be shown that it is a plugin specific problem.
