### ISSUE TITLE
entry.update webhook data missing some fields

### ISSUE THREAD

**Issue by martinkz** [ComfortablyCoding/strapi-plugin-publisher#51]
When the plugin publishes an entry, the resulting data sent to a webhook is missing some (or all) data, which would normally appear if you were to publish it manually. In one case, an image field is missing, whereas several other fields are showing correctly. In another case none of the fields were present, only meta data is present (e.g. id, createdAt, etc). 

The issue is that this entry.update event sent to the webhook is indistinguishable from any other update that is made by manually saving or publishing, and since it's missing some fields, it will lead to loss of data on the front end when it's re-built due to the webhook call.

Example webhook data when published by the plugin:

```
{
  "event": "entry.update",
  "createdAt": "2023-02-17T11:17:00.046Z",
  "model": "homepage",
  "uid": "api::homepage.homepage",
  "entry": {
    "id": 1,
    "title": "V 1",
    "text": "<p>Text v1</p>",
    "createdAt": "2023-02-17T11:10:48.660Z",
    "updatedAt": "2023-02-17T11:17:00.036Z",
    "publishedAt": "2023-02-17T11:17:00.000Z",
    "myToggle": false,
    "color": "#8f4343"
  }
}
```

Full data when publishing manually:

```
{
  "event": "entry.update",
  "createdAt": "2023-02-17T11:15:01.378Z",
  "model": "homepage",
  "uid": "api::homepage.homepage",
  "entry": {
    "id": 1,
    "title": "V 1",
    "text": "<p>Text v1</p>",
    "createdAt": "2023-02-17T11:10:48.660Z",
    "updatedAt": "2023-02-17T11:15:01.362Z",
    "publishedAt": null,
    "myToggle": false,
    "color": "#8f4343",
    "image": {
      "id": 1,
      "name": "soup.jpg",
      "alternativeText": null,
      "caption": null,
      "width": 526,
      "height": 789,
      "formats": {
        "small": {
          "ext": ".jpg",
          "url": "/uploads/small_soup_45628bd5e9.jpg",
          "hash": "small_soup_45628bd5e9",
          "mime": "image/jpeg",
          "name": "small_soup.jpg",
          "path": null,
          "size": 39.58,
          "width": 333,
          "height": 500
        },
        "medium": {
          "ext": ".jpg",
          "url": "/uploads/medium_soup_45628bd5e9.jpg",
          "hash": "medium_soup_45628bd5e9",
          "mime": "image/jpeg",
          "name": "medium_soup.jpg",
          "path": null,
          "size": 73.26,
          "width": 500,
          "height": 750
        },
        "thumbnail": {
          "ext": ".jpg",
          "url": "/uploads/thumbnail_soup_45628bd5e9.jpg",
          "hash": "thumbnail_soup_45628bd5e9",
          "mime": "image/jpeg",
          "name": "thumbnail_soup.jpg",
          "path": null,
          "size": 5.89,
          "width": 104,
          "height": 156
        }
      },
      "hash": "soup_45628bd5e9",
      "ext": ".jpg",
      "mime": "image/jpeg",
      "size": 76.5,
      "url": "/uploads/soup_45628bd5e9.jpg",
      "previewUrl": null,
      "provider": "local",
      "provider_metadata": null,
      "createdAt": "2023-02-14T14:21:19.105Z",
      "updatedAt": "2023-02-16T12:15:17.003Z"
    }
  }
}
```

**Comment by ComfortablyCoding** [comment]
Interesting. This seems to be the side effect setting only the value for the published date on trigger instead of resending all the data like strapi does for their publish.

I will look into this.

**Comment by maruthasalamr** [comment]
> When the plugin publishes an entry, the resulting data sent to a webhook is missing some (or all) data, which would normally appear if you were to publish it manually. In one case, an image field is missing, whereas several other fields are showing correctly. In another case none of the fields were present, only meta data is present (e.g. id, createdAt, etc).
> 
> The issue is that this entry.update event sent to the webhook is indistinguishable from any other update that is made by manually saving or publishing, and since it's missing some fields, it will lead to loss of data on the front end when it's re-built due to the webhook call.
> 
> Example webhook data when published by the plugin:
> 
> ```
> {
>   "event": "entry.update",
>   "createdAt": "2023-02-17T11:17:00.046Z",
>   "model": "homepage",
>   "uid": "api::homepage.homepage",
>   "entry": {
>     "id": 1,
>     "title": "V 1",
>     "text": "<p>Text v1</p>",
>     "createdAt": "2023-02-17T11:10:48.660Z",
>     "updatedAt": "2023-02-17T11:17:00.036Z",
>     "publishedAt": "2023-02-17T11:17:00.000Z",
>     "myToggle": false,
>     "color": "#8f4343"
>   }
> }
> ```
> 
> Full data when publishing manually:
> 
> ```
> {
>   "event": "entry.update",
>   "createdAt": "2023-02-17T11:15:01.378Z",
>   "model": "homepage",
>   "uid": "api::homepage.homepage",
>   "entry": {
>     "id": 1,
>     "title": "V 1",
>     "text": "<p>Text v1</p>",
>     "createdAt": "2023-02-17T11:10:48.660Z",
>     "updatedAt": "2023-02-17T11:15:01.362Z",
>     "publishedAt": null,
>     "myToggle": false,
>     "color": "#8f4343",
>     "image": {
>       "id": 1,
>       "name": "soup.jpg",
>       "alternativeText": null,
>       "caption": null,
>       "width": 526,
>       "height": 789,
>       "formats": {
>         "small": {
>           "ext": ".jpg",
>           "url": "/uploads/small_soup_45628bd5e9.jpg",
>           "hash": "small_soup_45628bd5e9",
>           "mime": "image/jpeg",
>           "name": "small_soup.jpg",
>           "path": null,
>           "size": 39.58,
>           "width": 333,
>           "height": 500
>         },
>         "medium": {
>           "ext": ".jpg",
>           "url": "/uploads/medium_soup_45628bd5e9.jpg",
>           "hash": "medium_soup_45628bd5e9",
>           "mime": "image/jpeg",
>           "name": "medium_soup.jpg",
>           "path": null,
>           "size": 73.26,
>           "width": 500,
>           "height": 750
>         },
>         "thumbnail": {
>           "ext": ".jpg",
>           "url": "/uploads/thumbnail_soup_45628bd5e9.jpg",
>           "hash": "thumbnail_soup_45628bd5e9",
>           "mime": "image/jpeg",
>           "name": "thumbnail_soup.jpg",
>           "path": null,
>           "size": 5.89,
>           "width": 104,
>           "height": 156
>         }
>       },
>       "hash": "soup_45628bd5e9",
>       "ext": ".jpg",
>       "mime": "image/jpeg",
>       "size": 76.5,
>       "url": "/uploads/soup_45628bd5e9.jpg",
>       "previewUrl": null,
>       "provider": "local",
>       "provider_metadata": null,
>       "createdAt": "2023-02-14T14:21:19.105Z",
>       "updatedAt": "2023-02-16T12:15:17.003Z"
>     }
>   }
> }
> ```

For me also same issue please fix the issue

**Comment by ComfortablyCoding** [comment]
@martinkz What strapi version are you on?

**Comment by maruthasalamr** [comment]
> @martinkz What strapi version are you on?

v4.4.4

**Comment by martinkz** [comment]
I'm using the latest version.

**Comment by maruthasalamr** [comment]
Please fix this issue

**Comment by ComfortablyCoding** [comment]
This should be fixed in v1.3.0 of the plugin

**Comment by maruthasalamr** [comment]
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:TypeError: isAnyToMany is not a function

**Comment by ComfortablyCoding** [comment]
Let's discuss this in #58
