### ISSUE TITLE
docs(README): add instructions for clean admin rebuild

### ISSUE THREAD

**Issue by rohitrathodxebia** [ComfortablyCoding/strapi-plugin-publisher#52]
Hi,

Recently I downloaded this plugin but it is not working. UI is not getting rendered on edit content as shown in the documentation image.

Thanks you in advance!!!

**Comment by ComfortablyCoding** [comment]
Try doing a clean build of the admin interface.

A clean build is done by deleting the `.cache` and `build` folder and the running the develop command

**Comment by rohitrathodxebia** [comment]
Thanks a lot it worked!!!

I would request you to please update the below section in your document - https://market.strapi.io/plugins/strapi-plugin-publisher
**From**
If the Publisher section does not appear after the plugin is enabled trigger a clean rebuild of the admin
**To**
If the Publisher section does not appear after the plugin is enabled than delete the auto generated folders `.cache` and `build` and run `yarn develop` or `npm develop` command.

**Comment by ComfortablyCoding** [comment]
Yw, and will do. Appreciate the suggestion.
