### ISSUE TITLE
When Schedule any contents i got this below error

### ISSUE THREAD

**Issue by maruthasalamr** [ComfortablyCoding/strapi-plugin-publisher#58]
using strapi plugin publisher version 1.3.0 strapi version 4.4.4
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:TypeError: isAnyToMany is not a function

**Comment by ComfortablyCoding** [comment]
Your strapi version probably does not have that function in the strapi utils. I will look into fixing that tonight, forgot to check what version that was added in.

**Comment by ComfortablyCoding** [comment]
This should be fixed in v1.3.1 of the plugin

**Comment by maruthasalamr** [comment]
Thanks
