### ISSUE TITLE
Plugin doesn't work with 4.8.0+

### ISSUE THREAD

**Issue by asans** [ComfortablyCoding/strapi-plugin-publisher#62]
Looks like it's having peer dependency version conflicts with newer Strapi versions that use react-intl 6+ where the plugin only states ^5+.

Due to this, npm install errors out and requires --force to install.

I tested the plugin with 4.8.2 and it does appear to work fine without any problems.

**Comment by BabyDino** [comment]
+1 running into the same issue

**Comment by asans** [comment]
The temporary workaround is to add an override in the package.json:

```
  "overrides": {
    "strapi-plugin-publisher": {
      "react-intl": "^6.0.0"
    }
  },
```

Still, it's not the right fix for this situation.

**Comment by BabyDino** [comment]
Feel better! And thank you as always :)

**Comment by ComfortablyCoding** [comment]
> Looks like typescript dependency also should be updated to allow 5.x

Typescript? This plugin does not have a dependency on typescript.

**Comment by asans** [comment]
My bad.  The new react-intl 6.x is the one that has that dependency.  So when upgrading and using react-intl 6 and typescript 5, we get this error.  So it's technically react-intl, not this plugin.

**Comment by ComfortablyCoding** [comment]
This should be fixed in the latest release
