### ISSUE TITLE
Users with restricted publishing capabilities can set the date of publication.

### ISSUE THREAD

**Issue by marromugi** [ComfortablyCoding/strapi-plugin-publisher#63]
### detail
Even users in roles that restrict the permission of users to publish articles can use Publisher to set publication settings.
Is it possible to restrict the functionality of Publisher to users whose article publishing privileges are controlled, such as the Author privilege?

### version
strapi: 4.6.1
strapi-plugin-publisher: 1.2.0

<img width="266" alt="image" src="https://user-images.githubusercontent.com/101984097/226284702-3783ac09-a54f-42cc-ab09-c58adb8a1218.png">

### Fix
I think that adding a Policy will prevent unauthorized users from setting reservations
(although it may be difficult to be consistent with the UI).

```js
const PUBLISH_ACTION = 'plugin::content-manager.explorer.publish';
const utils = require('@strapi/utils');
const { PolicyError } = utils.errors;

module.exports = async (ctx, config, { strapi }) => {
	const user = ctx.state.user;
	const body = ctx.request.body;

	if (body.data && user.roles) {
		const entityUid = body.data.entitySlug;
		const roles = await strapi.entityService.findMany('admin::role', {
			filters: {
				id: {
					$in: user.roles.map((r) => r.id),
				},
			},
			populate: ['permissions'],
		});
		const canCreate = roles.some((r) =>
			r.permissions.some((p) => p.action === PUBLISH_ACTION && p.subject === entityUid)
		);

		return canCreate;
	}

	throw new PolicyError('You dont have a permission to publish this content');
};

```

**Comment by phumcentral** [comment]
@marromugi What should the fixed code path be in?

**Comment by IvoNet** [comment]
Please fix this problem, so that I do not have to configure a policy. It should adhere to the restrictions and now "authors" do not have publishing rights in my setup and now they can set one in the future, which they should not be able to.

**Comment by ComfortablyCoding** [comment]
I will have a look at this again over the next few days. RBAC has come a long way in terms of usage in plugins since this was originally built.

**Comment by ComfortablyCoding** [comment]
Closing this in favour of #34 as its a duplicate issue. I have opened a PR (#88) that should fix this issue. Feel free to test it out, will merge it in the next day or two if I dont see any issues.
