### ISSUE TITLE
How to change the Time intervel using strapi Date and Time picker

### ISSUE THREAD

**Issue by maruthasalamr** [ComfortablyCoding/strapi-plugin-publisher#75]
As a strapi user admin i need to set the published/unpublished date and time. The time picker is currently showing one minutes time interval but i need to have this in 30 minutes time interval.

Currently Behaviour

<img width="315" alt="image" src="https://github.com/ComfortablyCoding/strapi-plugin-publisher/assets/78694065/3f8d0a4d-8e19-45f8-bfa8-0adfcf3f5236">

System

Node.js version: 14.19.1
NPM version:9.2.0
Strapi version: 4.9.1
strapi plugin publisher : 1.3.1
Database: postgres
Operating system: Mac Os

**Comment by ComfortablyCoding** [comment]
The datetime picker step can be set via the `components.dateTimePicker.step` setting (added in #36).
