### ISSUE TITLE
Date not visible when screen too small

### ISSUE THREAD

**Issue by Dirvann** [ComfortablyCoding/strapi-plugin-publisher#76]
When selecting the date, the date box becomes too small on a small screen. 
Solution would be to modify the underlying DateTime helper plugin with css. 

Current:

![image](https://github.com/ComfortablyCoding/strapi-plugin-publisher/assets/26393450/4ca65a9e-34c2-444d-806c-8773c10aba54)

Wanted:

![image](https://github.com/ComfortablyCoding/strapi-plugin-publisher/assets/26393450/88085793-cd54-43b2-afe4-2e50200e4f11)

Adding "flex-direction: column" to the div surrounding the date and time boxes works. But I don't know how to implement this in the code:

![image](https://github.com/ComfortablyCoding/strapi-plugin-publisher/assets/26393450/2f3a3323-05ef-4c16-9ce8-de2b6a5eb662)

**Comment by Dirvann** [comment]
Indeed I might make a PR on the strapi design system for the component to have that fix included. 

Custom css would be amazing! Thanks

**Comment by ComfortablyCoding** [comment]
I had a try at this but it does not look like the DateTimePicker (the component being used here) supports classNames or custom css. This makes it impossible to apply any customs styles. We will need to way for https://github.com/strapi/design-system/issues/860
