### ISSUE TITLE
Missing module dependency yup

### ISSUE THREAD

**Issue by asans** [ComfortablyCoding/strapi-plugin-publisher#77]
I was running strapi 4.10.5 and 4.10.6. Previously, things worked as expected, but today, when I had to revert and downgrade strapi to 4.10.5 due to a bug in 4.10.6, I could no longer start up strapi due to a missing yup module dependency.

```
Error: Could not load js config file /Users/asans/proj/vpm-marketing/apps/strapi-cms/node_modules/strapi-plugin-publisher/strapi-server.js: Cannot find module 'yup'
```

The issue stems from the `server/config/schema.js` file requiring yup module, which is not included as a dependency in package.json.

Perhaps there was an implicit assumption that strapi or some other module happened to include this module and it worked.  But that module perhaps took out this dependency, which then started causing this problem.

Regardless of the issue, since this is a dependency for the plugin, it should include it in dependencies.  While hoisting could have covered this problem in npm or yarn, pnpm would have split out errors.

**Comment by ComfortablyCoding** [comment]
It's a peer dependency of the plugin and strapi (which is the core) should and still does include it. Not sure why you would receive that error.

I did have them listed as peerDeps (which I believe are not installed anyways) but strapi tends to bump major dep versions without notice causing dependant plugins to break.

I will look into adding it back somehow. Possibly with a * so versions do not effect it but it's still listed.

**Comment by asans** [comment]
I see the peer dependency listed is for @strapi/strapi, not yup.  Even if strapi itself includes the yup dependency, it's not a good idea to make implicit assumption here.  Transitive dependencies end up causing issues (you can read more about this [here](https://pnpm.io/motivation#creating-a-non-flat-node_modules-directory)) especially for more "proper" package managers like pnpm.  It also causes issues should your module rely on a behavior in a particular version of yup that may get updated, which then may break your code. 

My recommendation here if to explicitly declare a dependency (not peer or dev) to yup.  By doing this, it says that your code has explicit dependency on a specific module, which communicates to the plugin users what your code relies on.  It also ensures that you don't end up with changing behavior should yup be updated or removed from strapi, for example.

Specifying a peer dependency may also be ok, but it would depend on whether it's more or a application wide requirement. This would make more sense for high level frameworks like react and strapi.

**Comment by ComfortablyCoding** [comment]
Upon reading up about it a bit more, you are correct. I have added these as direct dependencies in #84 and should be in the next release

**Comment by asans** [comment]
@ComfortablyCoding I see that you committed the change, but a new version was not released.  Would you be able to push out the new version with this fix?

**Comment by ComfortablyCoding** [comment]
Should have a new version published over the weekend.

**Comment by ComfortablyCoding** [comment]
v1.3.7 has been released with these changes
