### ISSUE TITLE
Entry crash after Add a publish date - TypeError: b.toISOString is not a function

### ISSUE THREAD

**Issue by bobkataboo** [ComfortablyCoding/strapi-plugin-publisher#81]
Strapi version: 4.11.1
Plugin version: 1.3.5

Hello, I just installed this plugin and wanted to test it out. However, each time that I Add a publish date to an entry the frontend crashes. Nothing helps and I cannot open this entry anymore. 

The error I get is TypeError: b.toISOString is not a function
![image](https://github.com/ComfortablyCoding/strapi-plugin-publisher/assets/56256086/c244e2d9-5265-4e4d-a377-475fa2f331bb)

Please help

**Comment by Dirvann** [comment]
I have the same issue

**Comment by ComfortablyCoding** [comment]
I assume strapi  changed something again. Thanks for the report, I will check this.

**Comment by ComfortablyCoding** [comment]
This should be fixed in the latest release.
