### ISSUE TITLE
[bug] "Publisher" doesn't check required fields

### ISSUE THREAD

**Issue by web-admin** [ComfortablyCoding/strapi-plugin-publisher#89]
Hi,

Today I found out a thing that shouldn't happen. "Publisher" publish an entry even if required fields are empty.

1. Open an entry with any required fields (leave these fields empty).
2. Set up the publish date in "Publisher".
3. When the chosen date will come the "Publisher" publish an entry ignoring empty, required fields.
4. What we get is broken API and finally page doesn't work as suppose to do.

**Comment by ComfortablyCoding** [comment]
How are you creating (or resaving) the entry without the required field set?

The only way i see this being possible was the required field(s) being added after content was already created in the collection. The expexctation though is that these entities are resaved with the required data. I will look into how easy it is to check these required field.

P.S. I tried this in the admin and even with a required field I can still save and publish the entity, not sure if this is a bug or not though (v4.11.7).

**Comment by web-admin** [comment]
I'm using 4.11.3 (an update to 4.11.4 broke the dates in Strapi which I mentioned here: https://github.com/strapi/strapi/issues/17348).

So in ver. 4.11.3 I can save an entry with empty required fields but cannot publish it which seems to be working good (I do not know how it works in 4.11.7). But if I set up a date/hour in Publisher and this date/hour comes then entry is published. Publisher doesn't check required fields at all and just publish everything without any validation.

**Comment by web-admin** [comment]
Hi,

Any progress here?

Once again I checked how it works in Strapi 4.11.3:
1. Create a new entry (do NOT add any content at all) and SAVE it (not PUBLISH).
2. Set up a date in PUBLISHER.
3. If chosen date comes then the PUBSLIHER publish an EMPTY entry.

P.S. I cannot publish an entry by pressing PUBLISH button - Strapi correctly marked required fields.

**Comment by ComfortablyCoding** [comment]
No progress as of yet.

**Comment by ComfortablyCoding** [comment]
This should be fixed in the latest release.
