### ISSUE TITLE
Feature Request: Adding Dutch Language Support

### ISSUE THREAD

**Issue by AliKdhim87** [ComfortablyCoding/strapi-plugin-publisher#97]
**Feature Request: Adding Dutch Language Support**

**Summary:**
I've been working on a Pull Request intended to add Dutch language support to the package. This addition aims to enhance the package's accessibility and usability for Dutch-speaking users.

**PR Details:**
- PR Title:  adding Dutch language support 
- PR Link:  https://github.com/ComfortablyCoding/strapi-plugin-publisher/pull/98

**Testing:**
While attempting to test the Dutch language support for the "strapi-plugin-publisher" locally, I encountered a browser freezing issue. I explored two testing methods:

- Using `yarn link`: I faced the browser freeze after linking the plugin via yarn link.

- Copying the Plugin: Manually copying the plugin to `src/plugins/strapi-plugin-publisher` also resulted in the same browser hang.

I'm excited about the opportunity to contribute to the project and make it more inclusive. Looking forward to your feedback and suggestions. Let's work together to make the package even better!

Thank you,
Ali Kadhim

**Comment by ComfortablyCoding** [comment]
Could be something else that may be causing it, Just adding the translation should not have this effect.

Thanks a lot for the PR, I have merged it and it should be in the next release.
